extend-exclude = [
  "solvers/cpp/cmake-conan/**"
]
target-version = "py314"

[lint]
select = ["ALL"]

ignore = [
  "COM812",
  "D10",
  "FIX",
  "ISC001",
  "PLR2004",
  "S101",
  "TD002",
  "TD003"
]

[lint.pydocstyle]
convention = "pep257"

[lint.per-file-ignores]
".github/scripts/*.py" = [
  "T201" # print
]
