name: CMake project setup
description: Setup cmake, conan and CMakeUserPresets.json

runs:
  using: composite
  steps:
    - name: Install CMake
      # TODO: Install cmake through mise
      uses: lukka/get-cmake@9e07ecdcee1b12e5037e42f410b67f03e2f626e1 # v4.2.1

    - name: Setup Conan Client
      # TODO: Setup only conan package cache here and use conan through mise
      uses: conan-io/setup-conan@2f4bd34e8e0af00e1a77a66e1d284e06d71d703f # v1.3.0
      with:
        cache_packages: true

    - name: Prepare files
      run: |
        cp .github/files/CMakeUserPresets.json solvers/cpp/
        cp .github/files/conan-profile-clang-with-libc++ solvers/cpp/
        cp .github/files/conan-profile-gcc-libstd++-for-clang solvers/cpp/
      shell: bash
