name: CMake project setup
description: Setup cmake, conan and CMakeUserPresets.json

runs:
  using: composite
  steps:
    - name: Install CMake
      # TODO: Install cmake through mise
      uses: lukka/get-cmake@bb2faa721a800324b726fec00f7c1ff7641964d1 # v4.2.0

    - name: Setup Conan Client
      # TODO: Setup only conan package cache here and use conan through mise
      uses: conan-io/setup-conan@09566912d661de90608308897a4d513e850c04e8 # v1.2.0
      with:
        cache_packages: true

    - name: Prepare files
      run: |
        cp .github/files/CMakeUserPresets.json solvers/cpp/
        cp .github/files/conan-profile-gcc-libstd++-for-clang solvers/cpp/
      shell: bash
