name: CMake project setup
description: Setup cmake, conan and CMakeUserPresets.json

runs:
  using: composite
  steps:
    - name: Install CMake
      # TODO: Install cmake through mise
      uses: lukka/get-cmake@628dd514bed37cb0a609e84a6186cbbaa2fc0140 # v4.1.2

    - name: Setup Conan Client
      # TODO: Setup only conan package cache here and use conan through mise
      uses: conan-io/setup-conan@09566912d661de90608308897a4d513e850c04e8 # v1.2.0
      with:
        cache_packages: true

    - name: Prepare CMakeUserPresets.json
      run: cp .github/CMakeUserPresets.json solvers/cpp/CMakeUserPresets.json
      shell: bash
