name: CMake project setup
description: Setup cmake, conan and CMakeUserPresets.json
inputs:
  conan-cache-key-prefix:
    description: Prefix for the conan cache key
    required: true
outputs:
  conan-cache-matched-key:
    description: Cache restore key used to restore Conan packages
    value: ${{ steps.cache-conan-packages.outputs.cache-matched-key }}

runs:
  using: composite
  steps:
    - id: init
      run: |
        # Initialize cmake-project-setup action
        "${GITHUB_ACTION_PATH}/init.sh"
      shell: bash

    - id: cache-conan-packages
      name: Restore Conan packages cache
      uses: actions/cache/restore@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
      with:
        # Use an intentionally non-matching suffix so that restores only use the prefixes below.
        # The full key is only used when saving a new cache entry.
        key: ${{ inputs.conan-cache-key-prefix }}-${{ hashFiles('solvers/cpp/conan.lock') }}-partial-match-only
        path: ${{ steps.init.outputs.conan-cache-path }}
        restore-keys: |
          ${{ inputs.conan-cache-key-prefix }}-${{ hashFiles('solvers/cpp/conan.lock') }}-
          ${{ inputs.conan-cache-key-prefix }}-

    - name: Install CMake
      # TODO: Install cmake through mise
      uses: lukka/get-cmake@9e07ecdcee1b12e5037e42f410b67f03e2f626e1 # v4.2.1

    - id: sccache-version
      run: |
        # Determine sccache version
        set -euo pipefail
        pushd solvers/cpp
        sccache_version=$(mise tool sccache --active | tr -d '\n')
        echo "version=v${sccache_version}" | tee -a "${GITHUB_OUTPUT}"
        popd
      shell: bash

    - name: Setup sccache
      # TODO: Use sccache from mise when it's possible to avoid installing it via this action
      uses: Mozilla-Actions/sccache-action@7d986dd989559c6ecdb630a3fd2557667be217ad # v0.0.9
      with:
        version: ${{ steps.sccache-version.outputs.version }}

    - run: |
        # Enable sccache for C++
        echo "SCCACHE_GHA_ENABLED=true" | tee -a "${GITHUB_ENV}"
      shell: bash

    - run: |
        # Prepare files
        cp .github/files/CMakeUserPresets.json solvers/cpp/
        cp .github/files/conan-profile-clang-with-libc++ solvers/cpp/
        cp .github/files/conan-profile-gcc-libstd++-for-clang solvers/cpp/
      shell: bash
