name: mise + uv project setup
description: Setup tools for uv project and install dependencies
inputs:
  cache-mode:
    default: use
    description: "Mode of operation regarding cache: 'prepare-check-match', 'prepare' or 'use'"
    required: false
  directory:
    description: Directory containing uv project.
    required: true
outputs:
  match:
    description: In prepare-check-match mode, whether the cache matches.
    value: ${{ steps.prepare-cache-check.outputs.match || 'false' }}

runs:
  using: composite
  steps:
    - id: init
      env:
        CACHE_MODE: ${{ inputs.cache-mode }}
        DIRECTORY: ${{ inputs.directory }}
      run: |
        # Prepare variables
        "${GITHUB_ACTION_PATH}/init.sh"
      shell: bash

    - id: prepare-check-cache-match
      if: steps.init.inputs.cache-mode == 'prepare-check-match'
      name: uv cache check
      uses: actions/cache/restore@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
      with:
        key: ${{ steps.init.outputs.cache-key }}
        lookup-only: true
        path: ${{ steps.init.outputs.cache-paths }}

    - id: prepare-cache-check

      env:
        CACHE_MODE: ${{ inputs.cache-mode }}
        EXACT_MATCH: ${{ steps.prepare-check-cache-match.outputs.cache-hit }}
      run: |
        # Check if cache mode is 'prepare-check-match' and exact match is true
        match=false
        if [[ "${CACHE_MODE}" == "prepare-check-match" && "${EXACT_MATCH}" == "true" ]]; then
          echo "Exact match found in prepare mode. Skipping the rest of the action"
          match=true
        fi
        echo "::group::Outputs from cache-check"
        echo "match=${match}" | tee -a "${GITHUB_OUTPUT}"
        echo "::endgroup::"
      shell: bash

    - id: cache-restore
      if: inputs.cache-mode != 'prepare-check-match'
      name: uv cache restore
      uses: actions/cache/restore@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
      with:
        key: ${{ steps.init.outputs.cache-key }}
        path: ${{ steps.init.outputs.cache-paths }}
        restore-keys: ${{ steps.init.outputs.cache-restore-keys }}

    - if: inputs.cache-mode != 'prepare-check-match' && steps.cache-restore.outputs.cache-hit != 'true'

      env:
        DIRECTORIES: ${{ steps.init.outputs.uv-install-directories }}
      run: |
        # Install uv dependencies

        set -euo pipefail

        # Unset in case it is set by an earlier run of this action
        unset UV_OFFLINE

        for dir in ${DIRECTORIES}; do
          echo "::group::Install uv dependencies: ${dir}"
          pushd "${dir}"
          uv sync --locked
          popd
          echo "::endgroup::"
        done

        first_dir_with_uv=$(echo "${DIRECTORIES}" | head -n 1)
        echo "::group::Prune uv cache"
        pushd "${first_dir_with_uv}"
        # --ci switch removes build-system dependencies, unless they are pinned to specific version
        #uv cache prune --ci
        uv cache prune
        popd
        echo "::endgroup::"
      shell: bash

    - name: Save cache
      if: inputs.cache-mode == 'prepare' && steps.cache-restore.outputs.cache-hit != 'true'
      uses: actions/cache/save@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
      with:
        key: ${{ steps.cache-restore.outputs.cache-primary-key }}
        path: ${{ steps.init.outputs.cache-paths }}

    - if: inputs.cache-mode != 'prepare-check-match'
      env:
        DIRECTORIES: ${{ steps.init.outputs.uv-install-directories }}
      run: |
        # Ensure dependencies are installed properly
        set -eu
        for dir in ${DIRECTORIES}; do
          echo "::group::Ensure dependencies: ${dir}"
          pushd "${dir}"
          uv sync --locked --offline
          popd
          echo "::endgroup::"
        done
      shell: bash

    - if: inputs.cache-mode != 'prepare-check-match'
      run: |
        # Adjust environment for rest of workflow
        echo "::group::Environment changes for rest of workflow"
        echo "Set uv to locked mode: UV_LOCKED=1"
        echo "UV_LOCKED=1" >> "${GITHUB_ENV}"
        echo "Set uv to offline mode: UV_OFFLINE=1"
        echo "UV_OFFLINE=1" >> "${GITHUB_ENV}"
        echo "::endgroup::"
      shell: bash
