[tools]
"npm:pyright" = "1.1.405"
"pipx:mypy" = "1.18.2"

[tasks.check]
depends = [
  "check:mypy",
  "check:pyright",
  "check:pytest",
]

[tasks."check:mypy"]
run = """
# Run mypy
pythonExecutable=$(uv python find)
pythonVersion=$(cat pyproject.toml | yq -p toml '.project.requires-python' | sed 's/>=//')
set -x
mypy --python-executable "${pythonExecutable}" --python-version "${pythonVersion}" . -v
"""

[tasks."check:pyright"]
run = "uv run pyright"

[tasks."check:pytest"]
run = "uv run pytest"

[tasks.fix]
depends = []
