[tools]
"npm:pyright" = "1.1.405"
"pipx:mypy" = "1.18.2"

[tasks.check]
depends = [
  "check:mypy",
  "check:pyright",
  "check:pytest",
]

[tasks."check:mypy"]
run = """
# Run mypy
pythonExecutable=$(uv python find)
echo "Running mypy with python executable: ${pythonExecutable}"
set -x
mypy --python-executable "${pythonExecutable}" --python-version 3.13 . -v
"""

[tasks."check:pyright"]
run = "uv run pyright"

[tasks."check:pytest"]
run = "uv run pytest"

[tasks.fix]
depends = []
