[tools]
"npm:pyright" = "1.1.405"
"pipx:mypy" = "1.18.1"

[tasks.check]
depends = [
  "check:mypy",
  "check:pyright",
  "check:pytest",
]

[tasks."check:mypy"]
run = "mypy --python-executable $(uv python find) ."

[tasks."check:pyright"]
run = "uv run pyright"

[tasks."check:pytest"]
run = "uv run pytest"

[tasks.fix]
depends = []
