name: Cleanup GitHub runner caches after Mise updates
on:
  pull_request:
    types:
      - closed
  workflow_dispatch:
permissions: {}

jobs:
  cleanup:
    name: Cleanup caches
    runs-on: ubuntu-24.04
    permissions:
      actions: write
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Cleanup

        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
          # renovate: datasource=github-releases depName=jdx/mise
          MISE_VERSION: v2025.10.1
        run: ./.github/scripts/delete_obsolete_mise_caches.py
