name: Checks - Python project
on:
  workflow_call:
    inputs:
      directory:
        description: Python project directory
        required: true
        type: string
  workflow_dispatch:
    inputs:
      directory:
        description: Python project directory
        options:
          - aoc-main
          - solvers/python
        required: true
        type: choice
permissions:
  contents: read

jobs:
  # Every check that also needs a uv virtual environment
  checks:
    name: Run checks
    runs-on: ubuntu-24.04
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Restore mise project
        uses: ./.github/actions/mise-project-setup
        with:
          directory: ${{ inputs.directory }}

      - name: Restore uv project
        uses: ./.github/actions/uv-project-setup
        with:
          directory: ${{ inputs.directory }}

      - parallel:
          - name: check:mypy

            run: mise run check:mypy
            shell: bash
            working-directory: ${{ inputs.directory }}

          - name: check:pyright

            run: mise run check:pyright
            shell: bash
            working-directory: ${{ inputs.directory }}

          - name: check:pytest

            run: mise run check:pytest
            shell: bash
            working-directory: ${{ inputs.directory }}
