name: Check - clang-tidy
on:
  workflow_call:
permissions:
  contents: read

jobs:
  clang-tidy:
    strategy:
      matrix:
        include:
          - name: Clang Debug
            configurePreset: ci-clang-tidy-debug
          - name: Clang Release
            configurePreset: ci-clang-tidy-release

    name: ${{ matrix.name }} - Clang tidy
    runs-on: ubuntu-24.04
    timeout-minutes: 30

    defaults:
      run:
        working-directory: solvers/cpp

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          submodules: true

      - name: Setup CMake project
        uses: ./.github/actions/cmake-project-setup

      - name: Configure CMake project
        uses: lukka/run-cmake@v10.8
        with:
          cmakeListsTxtPath: solvers/cpp/CMakeLists.txt
          configurePreset: ${{ matrix.configurePreset }}

      - name: Remove .clang-format
        # clang-tidy will fail if .clang-format file contains keys that are not
        # supported by clang-format in the same LLVM version as clang-tidy is.
        # This workflow is only checking for errors and the formatting is only
        # relevant when applying fixes.
        run: rm .clang-format

      - name: Run clang-tidy
        run: run-clang-tidy -p build
