name: CI - Solvers - C++
on:
  workflow_call:
    inputs:
      packages-hash-macos:
        description: Hash of installed packages on MacOS
        required: true
        type: string
      packages-hash-ubuntu:
        description: Hash of installed packages on Ubuntu
        required: true
        type: string
  workflow_dispatch:
permissions:
  contents: read

jobs:
  # DEBUG
  debug-ubuntu:
    runs-on: ubuntu-24.04
    steps:
      - run: |
          mods="$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          eval "${mods}"

          brewCache=$(brew --cache)
          ls -la "${brewCache}"/ || true

          brew cleanup -s -v -n --prune=all
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Setup homebrew packages
        uses: ./.github/actions/homebrew-packages-setup
        with:
          cache-mode: use
          packages-hash-to-use: ${{ inputs.packages-hash-ubuntu }}

      - run: |
          set -x
          echo "HOMEBREW_PREFIX=${HOMEBREW_PREFIX}"
          ls -la "${HOMEBREW_PREFIX}"/ || true
          ls -la "${HOMEBREW_PREFIX}"/opt/ || true
          ls -la "${HOMEBREW_PREFIX}"/opt/gcc/ || true
          ls -la "${HOMEBREW_PREFIX}"/opt/gcc/include/ || true
          ls -la "${HOMEBREW_PREFIX}"/opt/gcc/include/c++/ || true
          ls -la "${HOMEBREW_PREFIX}"/opt/gcc/include/c++/15/ || true
          brewCache=$(brew --cache)
          ls -la "${brewCache}"/ || true

        shell: bash

  debug-macos:
    runs-on: macos-15
    steps:
      - run: |
          set -x
          brewCache=$(brew --cache)
          ls -la "${brewCache}"/ || true

          brew cleanup -s -v
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Setup homebrew packages
        uses: ./.github/actions/homebrew-packages-setup
        with:
          cache-mode: use
          packages-hash-to-use: ${{ inputs.packages-hash-macos }}

      - run: |
          set -x
          echo "HOMEBREW_PREFIX=${HOMEBREW_PREFIX}"
          ls -la "${HOMEBREW_PREFIX}"/ || true
          ls -la "${HOMEBREW_PREFIX}"/opt/ || true
          ls -la "${HOMEBREW_PREFIX}"/opt/gcc/ || true
          ls -la "${HOMEBREW_PREFIX}"/opt/gcc/include/ || true
          ls -la "${HOMEBREW_PREFIX}"/opt/gcc/include/c++/ || true
          ls -la "${HOMEBREW_PREFIX}"/opt/gcc/include/c++/15/ || true
          brewCache=$(brew --cache)
          ls -la "${brewCache}"/ || true

        shell: bash


  # Checks
  build-test-run:
    uses: ./.github/workflows/cpp-build-test-run.yaml
    with:
      packages-hash-macos: ${{ inputs.packages-hash-macos }}
      packages-hash-ubuntu: ${{ inputs.packages-hash-ubuntu }}

  check-clang-format:
    uses: ./.github/workflows/mise-task.yaml
    with:
      directory: solvers/cpp
      task: check:clang-format

  # Check for all green CI for C++
  check:
    if: always()
    needs:
      - build-test-run
      - check-clang-format
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    steps:
      - uses: re-actors/alls-green@05ac9388f0aebcb5727afa17fcccfecd6f8ec5fe # v1.2.2
        with:
          jobs: ${{ toJSON(needs) }}
